#!/usr/bin/env php

<?php
print PHP_EOL."Git pre-commit hook".PHP_EOL;
$projectName = basename(getcwd());
$log = $projectName."Test.log";
exec('rm -R deprecated/doc');
exec('phpdoc', $docOutput, $docReturnCode);
foreach($docOutput as $line) {
    if (strpos($line, 'No ')!==false) {
        $docReturnCode = 1;    
    }
}
exec('phpcs --standard=PSR2 -p *.php',$PSROutput, $PSRReturnCode);
exec('phpunit', $testOutput, $testReturnCode);

if($testReturnCode !== 0) {
    print "Test suite for $projectName failed: ";
    $output = PHP_EOL.var_export($testOutpuit, true).PHP_EOL;
    file_put_contents($log, $output);
    exit(1);
} elseif($docReturnCode !== 0) {
    print "Comments not complete for $projectName";
    $output = PHP_EOL.var_export($docOutput, true).PHP_EOL;
    file_put_contents($log, $output);
    exit(1);
} elseif ($PSRReturnCode !== 0) {
    print "$projectName is not PSR2 compliant";
    $output = PHP_EOL.var_export($PSROutput, true).PHP_EOL;
    file_put_contents($log, $output);
    exit(1);
} else {
    print "PHPUnit: All tests for $projectName passed.".PHP_EOL
        ."PHPDoc: All comments for $projectName are valid.".PHP_EOL
        ."PHPCS: $projectName is PSR-2 compliant.".PHP_EOL;
    exit(0);
}
